/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
  const express = require("express");
  const fs = require("fs");

  const app = express();
  
  app.use(express.json());

  const fileData = fs.readFileSync("todos.json", "utf-8");
  const todos = JSON.parse(fileData)

  app.get("/todos", (req, res)=>{
    try{
      res.status(200).json(todos);
    }catch(error){
      res.status(500).json({
        message: error.message
      });
    }
  })

  app.get("/todos/:id", (req, res)=>{
    try{
      const id = req.params.id;
      const todo = todos.find((todo) => todo.id == id);
      
      if(!todo){
        return res.status(404).json({
          message: "Todo not Found"
        })
      }
      else{
        res.status(200).json(todo);
      }
    }catch(error){
      res.status(500).json({
        message: error.message,
      })
    }
  })

  app.post("/todos", (req, res)=>{
    try{
    const bodyData = req.body;
    
    const newTodo = {
      id: todos.length > 0 ? todos[todos.length - 1].id + 1 : 1,
      title: bodyData.title,
      completed: bodyData.completed,
      description: bodyData.description
    }

    todos.push(newTodo);
    fs.writeFileSync("todos.json", JSON.stringify(todos, null, 2));

    res.status(201).json({id: newTodo.id});
    }catch(error){
      return res.status(500).json({
        message: error.message,
      })
    }
  })

  app.put("/todos/:id", (req, res)=>{
    try{
      const id = Number(req.params.id);
      const todo = todos.find((todo) => todo.id == id);
  
      const updatedTodos = todos.map((todo) => {
        if(todo.id === id){
          return {
            ...todo,
            ...req.body,
          };
        }
        return todo;
      })

      if(!todo){
        return res.status(404).json({message: "Todo not found"})
      }

      else{
        fs.writeFileSync("todos.json", JSON.stringify(updatedTodos, null,2));
        res.status(200).json({message: "Todo Updated Successfully"})
      }
    }catch(error){
      return res.status(500).json({
        message: error.message
      })
    }
  })

  app.delete("/todos/:id",(req, res)=>{
    try{
      const id = req.params.id;
      const todo = todos.find((todo)=> todo.id == id)
      const result = todos.filter((todo) => todo.id != id);

      if(!todo){
        return res.status(404).json({
          message: "Not found"
        })
      }
      else{
        fs.writeFileSync("todos.json", JSON.stringify(result, null, 2));
      res.status(200).json({
        message: "Found and deleted"
      });
      }
    }catch(error){
      return res.status(500).json({
        message: error.message
      })
    }
  })
  
  //app.listen(3000);
  module.exports = app;